;------------------------------------------------------------------------------
; GBA Test Collection - GBA test ROMs written in ARM assembly.
; Copyright (C) 2021  Michelle-Marie Schiller
;------------------------------------------------------------------------------
; memory.inc - Useful memory addresses and sizes.
;------------------------------------------------------------------------------

MEM_BIOS = 0x00000000
MEM_ERAM = 0x02000000
MEM_IRAM = 0x03000000
MEM_MMIO = 0x04000000
MEM_PRAM = 0x05000000
MEM_VRAM = 0x06000000
MEM_ORAM = 0x07000000
MEM_ROM0 = 0x08000000
MEM_SRAM = 0x0E000000

Size_MEM_BIOS = 0x04000
Size_MEM_ERAM = 0x40000
Size_MEM_IRAM = 0x08000
Size_MEM_PRAM = 0x00400
Size_MEM_VRAM = 0x18000
Size_MEM_ORAM = 0x00400
Size_MEM_SRAM = 0x10000

;------------------------------------------------------------------------------
;------------------------------------------------------------------------------
